services:
  # API Service configuration
  - type: web
    name: test-formpad-service
    env: python
    region: ohio
    plan: starter
    branch: testing-testing
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn service.main:app --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.1