services:
  # API Service configuration
  - type: web
    name: test-formpad-service
    env: python
    region: ohio
    plan: starter
    branch: testing-testing
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn service.main:app --host 0.0.0.0 --port 10000
    buildFilter:
      paths:
      - service/**/*.py
      - service/**/*.yaml
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.1
      - key: PRODUCTION_URL
        fromService:
          type: web
          name: test-formpad-editor
          property: host
  #Web editor configuration
  - type: web
    name: test-formpad-editor
    env: static
    plan: starter
    branch: testing-testing
    rootDir: web
    buildCommand: yarn build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: test-formpad-service
          property: hostport